on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        uses: jdx/mise-action@v2
        env:
          MISE_GITHUB_TOKEN: ''

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install libsdl2-dev -y

      - name: Test
        run: cargo test --verbose

      - name: Build
        run: cargo build --verbose
